HEADERS=data.h dmsexception.h logreader.h  logsender.h
SOURCES=logreader.cpp main.cpp  logsender.cpp

dms:$(SOURCES) $(HEADERS)
	g++ $(SOURCES) -o dms

clean:
	@rm -f dms  dms2009* *.dat  *.txt  *.gch
